### ISSUE TITLE
Make review of Jupyter notebooks more convenient

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt-paper-figures#3]
Reviewing Jupyter notebooks directly on GitHub is not very convenient. [GitNotebooks](https://gitnotebooks.com/) can make the review process easier. As an example, I use the PR #1 for the `coast` example, which is already merged:

**GitHub**: https://github.com/GenericMappingTools/pygmt-paper-figures/pull/1/files
**gitnotebooks**: https://gitnotebooks.com/GenericMappingTools/pygmt-paper-figures/pull/1

Maybe this is helpful for use for writing and reviewing the examples for the PyGMT paper.

**Comment by seisman** [comment]
I've enabled it for this repository. Closing the issue.
